### ISSUE TITLE
Validate fails with nested objects

### ISSUE THREAD

**Issue by aosman-tibco** [khornberg/octokit.py#59]
This is slightly related to #51 as it's validating an optional parameter but the exception is worth looking into. The parameter `comments` contains a list object which the validation breaks on.

```python
pulls = Octokit(auth='installation', app_id=APP_ID, private_key=private_key).pulls
pulls.create_a_pull_request_review(owner='Foo', repo='demo', number=1, body='hello world', event='COMMENT')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/ahmed/pyenvchatback/lib/python3.6/site-packages/octokit/__init__.py", line 192, in _api_call
    self._validate(kwargs, parameter_map)
  File "/Users/ahmed/pyenv/chatback/lib/python3.6/site-packages/octokit/__init__.py", line 30, in _validate
    self._validate_required_params(required_params, cached_kwargs)
  File "/Users/ahmed/pyenv/chatback/lib/python3.6/site-packages/octokit/__init__.py", line 38, in _validate_required_params
    utils.walk_path(cached_kwargs, p.split('.'))
  File "/Users/ahmed/pyenv/chatback/lib/python3.6/site-packages/octokit/utils.py", line 24, in walk_path
    walk_path(obj[path[0]], path[1:])
KeyError: 'comments[]'

```

**Comment by khornberg** [comment]
Thanks! @aosman-tibco I'll have to look into it

**Comment by khornberg** [comment]
@aosman-tibco 0.10.1+ should fix this issue for you
0.10.2 has breaking changes due to the routes in octokitpy-routes having upstream breaking changes

**Comment by aosman-tibco** [comment]
Thanks for the quick fix @khornberg ! I just confirmed that this is now working.
